services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: banvic-data-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banvic_network

  meltano:
    image: meltano/meltano:latest-slim
    container_name: banvic-data-meltano
    volumes:
      - ./banvic-data:/project
      - meltano_plugins:/project/.meltano
    working_dir: /project
    tty: true
    entrypoint: ""
    environment:
      MELTANO_DATABASE_URI: postgresql+psycopg://postgres:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${MELTANO_CONFIG_DB}
      TARGET_POSTGRES_HOST: postgres
      TARGET_POSTGRES_PORT: ${POSTGRES_PORT}
      TARGET_POSTGRES_USER: ${POSTGRES_USER}
      TARGET_POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      TARGET_POSTGRES_DBNAME: ${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - banvic_network
    command: ["tail", "-f", "/dev/null"]

volumes:
  pgdata:
  meltano_plugins:

networks:
  banvic_network:
    driver: bridge
